-- entry point for packages
require('packages.tokyonight')
require('packages.oil')
require('packages.lsp-config')
require('packages.mini-icons')
require('packages.mini-starter')
require('packages.mini-statusline')
require('packages.tuxedo')
require('packages.goyo')
require('packages.treesitter')
require('packages.render-markdown')
